version: '3'


services: 
  instagram-api:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app
    depends_on: 
      - mongo
  mongo:
    image: mongo
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: vinicius
      MONGO_INITDB_ROOT_PASSWORD: abc12345

